server:
  port: 7724
#  V 1.0.4 uchun_port = 7716
#  V 1.0.5 uchun_port = 7717
#  V 1.0.6 uchun_port = 7718
#  V 1.0.7 uchun_port = 7719
#  V 1.0.8 uchun_port = 7720
#  V 1.0.9 uchun_port = 7721
#  V 1.1.0 uchun_port = 7722
#  V 1.1.1 uchun_port = 7723
#  V 1.1.2 uchun_port = 7724 +++
#  V 1.1.3 uchun_port = 7725
#  V 1.1.4 uchun_port = 7726


spring:
  datasource:
    username: jurabek
    password: 1111

    url: jdbc:postgresql://localhost:5432/sos
#    url: jdbc:postgresql://54.238.164.38:5432/sos
    driver-class-name: org.postgresql.Driver
    initialization-mode: always


  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers=true:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 172800000
      refresh-token:
        expiration: 1296000000

